# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Spark:
  Path: "/opt/spark"

Master:
  Name: master
  Image: "sshakeri/ubuntu"
  ImageTag: "spark_master"
  Replicas: 1
  Component: "spark-master"
  Cpu: "200m"
  Memory: "2048Mi"
  ServicePort: 7077
  ContainerPort: 7077
  ServiceType: NodePort

WebUi:
  Name: webui
  ServicePort: 32092
  ContainerPort: 8080

Worker:
  Name: worker
  Image: "sshakeri/ubuntu"
  ImageTag: "spark_worker"
  Replicas: 2
  Component: "spark-worker"
  Cpu: "100m"
  Memory: "500Mi"
  ContainerPort: 8081
  Autoscaling:
    Enabled: false
  ReplicasMax: 10
  CpuTargetPercentage: 50


Jupyter:
  Name: jupyter
  Image: "sshakeri/ubuntu"
  ImageTag: "jupyter"
  Replicas: 1
  Component: "jupyter"
  Cpu: "100m"
  Memory: "500Mi"
  ServicePort: 32090
  ContainerPort: 6660
  ServiceWebUIPort: 32091
  ContainerWebUIPort: 4040
  WebUIPort: 4040
  ServiceType: NodePort
  Enabled: true
  Ingress:
    Enabled: false
    Path: "/"
    Tls: []
  Persistence:
    Config:
      Enabled: false

